# Generated by Django 3.1.7 on 2023-03-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.FloatField()),
                ('spice_level', models.IntegerField(choices=[(1, 'No Spice'), (2, 'Mild'), (3, 'Spicy'), (4, 'Extra Spicy'), (5, 'Fire Spice')])),
            ],
        ),
    ]
