# Generated by Django 4.1.7 on 2023-04-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_review_name_review_user_alter_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.CreateModel(
            name="SizeOption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("size", models.PositiveSmallIntegerField()),
                ("price", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
