name: Deploy to Hetzner Cloud
on:
  workflow_dispatch:
    inputs:
      server_id:
        description: 'The ID of the Hetzner Cloud Server to deploy to'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: sudo apt-get install python3

    - name: Install pip
      run: sudo apt-get install python3-pip

    - name: Install dependencies
      run: |
        ssh root@${{ secrets.SERVER_IP }} 
        source ~/environments/benv/bin/activate
        cd bensdeli && pip install -r requirements.txt

    - name: Deploy to Hetzner Cloud
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./
        target: /root/bensdeli/
        port: 22

    - name: Start the app
      run: |
        ssh root@${{ secrets.SERVER_IP }} 
        source ~/environments/benv/bin/activate
        cd bensdeli/bensdeli && python3 manage.py runserver 0.0.0.0:8000
      